[project]
name = "gitcg"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "guyutongxue", email = "guyutongxue@163.com" }]
requires-python = ">=3.13"
dependencies = [
    "build>=1.2.2.post1",
    "cffi>=1.17.1",
    "jinja2>=3.1.4",
    "markupsafe>=3.0.2",
    "packaging>=24.2",
    "pdoc>=15.0.0",
    "protobuf>=5.29.1",
    "pycparser>=2.22",
    "pygments>=2.18.0",
    "pyproject-hooks>=1.2.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
